# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# along: If github.com is too slow, you can use hub.fastgit.xyz instead,
# or you can configure github proxy in /etc/hosts, such as `13.234.176.102 github.com`
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.3
    hooks:
      # A formatter for finding and removing unused import statements.
      - id: pycln
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://hub.fastgit.xyz/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://hub.fastgit.xyz/commitizen-tools/commitizen
    rev: v2.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
